rel:
	@cd Server;   make
	@cd Rtsp;   make

clean:
	@cd Server;   make clean
	@cd Rtsp;   make clean

cleanall:
	@cd Server;   make clean;   make cleanstream
	@cd Rtsp;   make clean;   make cleanstream